### ISSUE TITLE
Create and implement favicon

### ISSUE THREAD

**Issue by dargaCode** [dargaCode/LorenHernandezPortfolio#1]
A. 260x260 png with transparent background

B. An optional png with an opaque background

Transparent will be used for things like saved bookmarks on windows 8/10, osx, and ios. 

If it exists, opaque will be used for some other stuff but most importantly the tab icon. 

Transparent icons here just show the grey of the tab background:

<img width="203" alt="screen shot 2016-11-09 at 10 31 55 pm" src="https://cloud.githubusercontent.com/assets/12771651/20166889/a691f38c-a6cc-11e6-9004-3b69ab42a93d.png">

**Comment by dargaCode** [comment]
I'll use http://realfavicongenerator.net/ to set this up once we have the images

**Comment by lorenhgames** [comment]
So I ran the image thru the generator and I didn't like the 32x and 16x size icons it generated so I cleaned them up in photoshop and uploaded them... theyre just in the main folder for now. Stuck the original image in there too. Hope this works OK... not sure it'll look good but we can try it out <3

**Comment by dargaCode** [comment]
Looks great!

https://github.com/dargaCode/LorenHernandezPortfolio/commit/05b3a623b00e17ac5931b9643985e88d7ba68437 and https://github.com/dargaCode/LorenHernandezPortfolio/commit/6dddc103b0090f6a80f7778da753a4c65730cc17
