### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by dargaCode** [dargaCode/LorenHernandezPortfolio#13]

**Comment by dargaCode** [comment]
I think this will be like mailchimp where you need to sign up and then I can embed code?

**Comment by lorenhgames** [comment]
This is the code. It needs to be in every webpage (so I guess all of the sub pages too)

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-15562862-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by lorenhgames** [comment]
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-15562862-1', 'auto');
  ga('send', 'pageview');

</script>`

**Comment by lorenhgames** [comment]
it's not pasting... adding to the google doc

**Comment by dargaCode** [comment]
Ok I added the script. Can you check now if this is working, or is it tied to your real domain name somehow?

https://github.com/dargaCode/LorenHernandezPortfolio/commit/76f92bddb5edea54292afb4c793966c9240fca5e

**Comment by lorenhgames** [comment]
VERIFIED!
