### ISSUE TITLE
Add warning for puzzlestuck on mobile?

### ISSUE THREAD

**Issue by dargaCode** [dargaCode/LorenHernandezPortfolio#20]

**Comment by lorenhgames** [comment]
That could be really cool, yeah. Something like "In order to play Puzzlestuck, make sure you're using a Flash-enabled web browser!"

Small window seems like less of an issue? What do you think

**Comment by dargaCode** [comment]
https://github.com/dargaCode/LorenHernandezPortfolio/commit/f1ff6281c8e8b431e5c97fc3cf5533f205257d0a https://github.com/dargaCode/LorenHernandezPortfolio/commit/ba6814c0a1f0a200a09fbc26f257a23e52c05c05 https://github.com/dargaCode/LorenHernandezPortfolio/commit/1ac4d7205e473ff15e5021fa9e1812ec589a614f

Now detects flash enabled/disabled and shows/hides swf, save warning, and flash disabled warning appropriately

**Comment by dargaCode** [comment]
This change impacts:

- `/assets/css/game-puzzlestuck.css`
- `/assets/css/media-queries.css`
- `/assets/js/modernizr-flash-detect.js`
- `/puzzlestuck/index.html`
