### ISSUE TITLE
Replace iOS App Store Badge .svg with .png

### ISSUE THREAD

**Issue by dargaCode** [dargaCode/LorenHernandezPortfolio#30]
Once you have it saved out how you want it, I can plug it in

**Comment by dargaCode** [comment]
Fixed! https://github.com/dargaCode/LorenHernandezPortfolio/commit/5ee08f5a01aebf1151df475de459b9f465386ed1

**Comment by dargaCode** [comment]
Can be pushed to new server whenever

**Comment by lorenhgames** [comment]
Done!
