### ISSUE TITLE
Add information about save games to puzzlestuck

### ISSUE THREAD

**Issue by dargaCode** [dargaCode/LorenHernandezPortfolio#31]

**Comment by dargaCode** [comment]
https://github.com/dargaCode/LorenHernandezPortfolio/commit/88fbddb2e4231f94709ba12c632a61227928c91e

**Comment by dargaCode** [comment]
Added responsiveness https://github.com/dargaCode/LorenHernandezPortfolio/commit/098eeaecb709dcd8d1e2a62e2178a9d154d9a3ad

**Comment by lorenhgames** [comment]
Done! Looks good on firefox and mobile. I think Chrome is caching my page.

**Comment by dargaCode** [comment]
FYI I hid this element at the narrowest css breakpoint, since people can't possibly be playing the game at that width
