### ISSUE TITLE
Adjust colors if needed

### ISSUE THREAD

**Issue by dargaCode** [dargaCode/LorenHernandezPortfolio#6]
The ones that stick out to me as possibly needing a look:
- Link vs mouseover for Dungeon Sweeper
- Text vs footer background for main page

**Comment by dargaCode** [comment]
I added a new stylesheet called `homepage.css`, and put the colors for the homepage at the bottom like there are for the game stylesheets. https://github.com/dargaCode/LorenHernandezPortfolio/commit/9fe6922c14b4d8f4fc71565128bde53e0701e0d4

I also updated the names of the stylesheets for the games to be game-[gamename].css, so they sort better and are easier to navigate.

**Comment by lorenhgames** [comment]
Thank you!
Fixed these things and the Dudequest colors too :)
